[database]
username = "postgres"
password = "password"
host = "localhost"
port = 5432
database = "postgres"

[rabbitmq]
host = "localhost"
port = 5672  
queue = "bye"
routing_key = "bye"

[api]
host = "127.0.0.1"
port = 8443

[status_log_path]
path = "D:/data_files/"

[api_log_path]
get_schedule_path = "D:/data_files/api_log/get_schedule_data.log"
status_log_path = "D:/data_files/api_log/status_log_data.log"
